### ISSUE TITLE
HTTPS Security

### ISSUE THREAD

**Issue by tech4him1** [igk1972/netlify-cms-oauth-provider-go#2]
I noticed you are using HTTP URLs, instead of secure HTTPS ones. Is there a reason for this? Normally credentials shouldn't be sent/received in plain text:
https://github.com/igk1972/netlify-cms-oauth-provider-go/blob/ebf76de6a194ed60ec2a78d123715a999388d05b/main.go#L113-L115

**Comment by igk1972** [comment]
Thanka! 
Fixed https://github.com/igk1972/netlify-cms-oauth-provider-go/commit/01c5a48f5bb85e92524f9fc4a8a96bf0cb5e4260
My misprint, a misunderstanding.
But there's so a redirect to https

**Comment by tech4him1** [comment]
Great, thanks! A redirect to HTTPS is awesome, but the credentials still get transmitted in plain-text before the redirect, so thanks for fixing.
